version: '3.8'
services:
  spb-elasticsearch:
    image: docker.io/elasticsearch:7.11.1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - 'ES_JAVA_OPTS=-Xms1024m -Xmx1024m'
      - 'http.cors.enabled=true'
      - 'http.cors.allow-origin=http://localhost:48080'
      - 'discovery.type=single-node'

  elasticvue:
    image: cars10/elasticvue
    ports:
      - "48080:8080"

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_HOST_NAME: kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
